import type { Metadata } from "next";
import "../scss/main.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BottomNavMenu from "@/components/Mobile/BottomNavMenu/BottomNavMenu";
import HeaderMobile from "@/components/Mobile/HeaderMobile/HeaderMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderMobile />
        <Header />
        {children}
        <Footer />
        <BottomNavMenu />
      </body>
    </html>
  );
}
